(()=>{'use strict';const Q=[
['결정 방식','여러 선택지 중 하나를 빨리 정해야 한다.',['현재 정보로 우선 결정하고 필요하면 수정한다','가능한 변수를 더 확인한 뒤 결정한다'],['red','burgundy']],
['협업 방식','팀에서 담당자가 정해지지 않은 일이 생겼다.',['필요한 일을 먼저 맡고 사람들을 움직인다','각자의 강점을 보고 역할을 정리한다'],['red','gold']],
['갈등 대응','회의에서 내 의견에 강한 반대가 나왔다.',['핵심 쟁점을 바로 짚고 설득을 이어간다','왜 반대하는지 먼저 듣고 접점을 찾는다'],['orange','beige']],
['업무 습관','중요한 일을 시작할 때 가장 먼저 하는 것은?',['완료 기준과 순서를 적어 실행 계획을 만든다','전체 맥락과 숨은 문제부터 충분히 파악한다'],['gold','burgundy']],
['변화 대응','익숙한 업무 방식이 갑자기 바뀌었다.',['새 방식의 장점을 시험하며 빠르게 적응한다','검증된 부분은 유지하며 단계적으로 바꾼다'],['orange','brown']],
['관계 역할','모임에서 대화가 끊기고 어색해졌다.',['가벼운 화제를 던져 다시 흐름을 만든다','말이 적은 사람이 편하게 참여하도록 돕는다'],['orange','beige']],
['책임감','내 실수로 일정이 늦어질 가능성이 생겼다.',['즉시 알리고 해결책과 새 일정을 제시한다','영향 범위를 꼼꼼히 확인해 재발 방지까지 정리한다'],['red','gold']],
['정보 처리','설명이 복잡한 문제를 이해할 때 편한 방식은?',['핵심만 요약하고 직접 해보며 익힌다','자료를 비교하며 원리와 배경을 이해한다'],['orange','burgundy']],
['경계 설정','부탁을 계속 들어주느라 내 일이 밀리고 있다.',['상황을 분명히 설명하고 이번 부탁을 거절한다','가능한 범위를 정해 일부만 돕는다'],['red','brown']],
['일상 관리','예상보다 바쁜 한 주가 끝났다.',['밀린 집안일과 일정을 정리해야 개운하다','익숙한 방식으로 쉬며 생활 리듬부터 회복한다'],['gold','brown']],
['신뢰 관계','가까운 사람이 힘들어 보이지만 말을 아낀다.',['부담 주지 않고 평소처럼 곁에 있어 준다','조심스럽게 말을 걸고 충분히 들어준다'],['brown','beige']],
['평가 상황','좋은 결과를 냈는데 내 기여가 잘 드러나지 않았다.',['내가 한 일과 성과를 구체적으로 알린다','결과를 만든 과정과 팀의 기여를 함께 정리한다'],['burgundy','beige']]
];const R={red:{name:'선명한 붉은 단풍',title:'주도적으로 길을 여는 추진형',desc:'필요한 순간에 결정을 내리고 책임 있게 앞으로 나아갑니다. 모호한 상황에서도 행동의 출발점을 만들며, 문제를 피하기보다 정면으로 다루는 편이에요.',traits:['빠른 결단','분명한 표현','강한 추진력'],work:'목표를 잡으면 실행 속도를 높여 결과를 만듭니다.',conflict:'쟁점을 직접 확인하고 해결 방향을 제시합니다.',relation:'결정이 필요한 순간 중심을 잡는 역할',caution:'속도가 다른 사람에게 생각할 시간을 주세요.',match:'황금빛 은행잎',color:'#c53b31',filter:'none'},orange:{name:'밝은 주황 단풍',title:'변화에 강한 유연한 실행형',desc:'새로운 상황을 부담보다 가능성으로 받아들입니다. 직접 시도하며 배우고, 막힌 분위기를 자연스럽게 전환하는 현실적인 낙관성이 있어요.',traits:['빠른 적응','실용적 시도','활기찬 소통'],work:'완벽한 계획보다 작은 실행으로 답을 찾습니다.',conflict:'분위기를 풀고 현실적인 접점을 만듭니다.',relation:'사람과 일을 자연스럽게 이어주는 역할',caution:'흥미가 줄어든 뒤에도 마무리를 챙겨보세요.',match:'포근한 베이지 잎',color:'#df6f2d'},gold:{name:'황금빛 은행잎',title:'결과를 쌓아가는 체계형',desc:'해야 할 일을 구조화하고 안정적으로 완성합니다. 약속과 기준을 중요하게 여기며, 눈에 띄지 않는 과정까지 관리해 신뢰할 수 있는 결과를 만들어요.',traits:['체계적인 계획','높은 책임감','꾸준한 완성력'],work:'순서와 기준을 정해 빠짐없이 마무리합니다.',conflict:'사실과 역할을 정리해 재발 가능성을 줄입니다.',relation:'약속을 지키며 신뢰를 쌓는 역할',caution:'계획이 달라져도 실패로 받아들이지 마세요.',match:'선명한 붉은 단풍',color:'#dda928'},burgundy:{name:'깊은 자주 단풍',title:'본질을 파고드는 분석형',desc:'겉으로 드러난 답보다 원인과 맥락을 중요하게 봅니다. 충분히 생각한 뒤 내린 판단에는 깊이가 있으며, 복잡한 문제에서 다른 사람이 놓친 부분을 발견해요.',traits:['깊은 분석','신중한 판단','선명한 기준'],work:'자료와 맥락을 연결해 문제의 본질을 찾습니다.',conflict:'감정보다 원인과 논리를 먼저 정리합니다.',relation:'깊이 있는 조언과 관점을 더하는 역할',caution:'확신이 생길 때까지 시작을 미루지 마세요.',match:'차분한 갈색 잎',color:'#6f3040'},brown:{name:'차분한 갈색 잎',title:'흔들림 없이 지키는 안정형',desc:'급격한 변화보다 검증된 방식과 지속 가능한 리듬을 선호합니다. 쉽게 흔들리지 않고 맡은 자리를 지켜, 주변 사람이 안심하고 기댈 수 있게 해요.',traits:['안정적인 페이스','현실적인 판단','꾸준한 신뢰'],work:'무리하지 않는 방식으로 성과를 오래 유지합니다.',conflict:'선을 분명히 하되 관계가 깨지지 않게 조율합니다.',relation:'변함없는 태도로 중심을 지키는 역할',caution:'익숙함이 새로운 기회를 막지는 않는지 살펴보세요.',match:'깊은 자주 단풍',color:'#806440'},beige:{name:'포근한 베이지 잎',title:'사람 사이를 잇는 조율형',desc:'사람의 말과 감정을 세심하게 살피며 서로 다른 입장을 연결합니다. 자신의 존재감을 앞세우지 않아도 안전한 대화 분위기를 만들어 협력을 이끌어요.',traits:['세심한 경청','부드러운 조율','관계 감각'],work:'각자의 강점을 살려 함께 움직일 방법을 찾습니다.',conflict:'양쪽 입장을 듣고 받아들일 수 있는 접점을 만듭니다.',relation:'누구도 소외되지 않게 연결하는 역할',caution:'배려 때문에 내 의견을 뒤로 미루지 마세요.',match:'밝은 주황 단풍',color:'#c7ab83'}};
const $=s=>document.querySelector(s),ui={start:$('#start'),quiz:$('#quiz'),result:$('#result'),startBtn:$('#startBtn'),label:$('#qLabel'),now:$('#qNow'),bar:$('#bar'),cat:$('#category'),q:$('#question'),answers:$('#answers'),back:$('#backBtn'),leaf:$('#leaf'),name:$('#resultName'),title:$('#resultTitle'),desc:$('#resultDesc'),traits:$('#traits'),work:$('#work'),conflict:$('#conflict'),relation:$('#relation'),caution:$('#caution'),match:$('#match'),share:$('#shareBtn'),restart:$('#restartBtn')};let index=0,chosen=[],latest='red';function show(x){[ui.start,ui.quiz,ui.result].forEach(e=>e.hidden=e!==x);scrollTo({top:0,behavior:'smooth'})}function render(){const q=Q[index];ui.label.textContent=`QUESTION ${String(index+1).padStart(2,'0')}`;ui.now.textContent=index+1;ui.bar.style.width=`${(index+1)/Q.length*100}%`;ui.cat.textContent=q[0];ui.q.textContent=q[1];ui.answers.replaceChildren(...q[2].map((text,i)=>{const b=document.createElement('button');b.textContent=text;b.onclick=()=>answer(i);return b}));ui.back.hidden=index===0}function answer(i){chosen[index]=i;if(index<Q.length-1){index++;render()}else finish()}function finish(){const scores=Object.fromEntries(Object.keys(R).map(k=>[k,0]));Q.forEach((q,i)=>scores[q[3][chosen[i]]]++);latest=Object.keys(scores).sort((a,b)=>scores[b]-scores[a])[0];const r=R[latest];ui.result.style.setProperty('--leaf',r.color);ui.leaf.style.filter=`drop-shadow(0 9px 9px #48211430) sepia(.15) saturate(1.4)`;ui.leaf.style.color=r.color;ui.name.textContent=r.name;ui.title.textContent=r.title;ui.desc.textContent=r.desc;ui.traits.replaceChildren(...r.traits.map(t=>Object.assign(document.createElement('span'),{textContent:`# ${t}`})));['work','conflict','relation','caution','match'].forEach(k=>ui[k].textContent=r[k]);show(ui.result)}function restart(){index=0;chosen=[];render();show(ui.quiz)}function share(){const r=R[latest],url='https://www.survivaloffice.com/test/leaf-color/';if(!window.Kakao){alert('카카오톡 공유를 불러오지 못했습니다.');return}if(!Kakao.isInitialized())Kakao.init('eee6c2e01641161de9f217ba99c6a0da');Kakao.Link.sendDefault({objectType:'feed',content:{title:`나의 단풍색은 ${r.name}`,description:r.title,imageUrl:'https://www.survivaloffice.com/images/leaf-color/leaf-color-share.jpg',link:{mobileWebUrl:url,webUrl:url}},buttons:[{title:'나도 단풍색 알아보기',link:{mobileWebUrl:url,webUrl:url}}]})}ui.startBtn.onclick=()=>{render();show(ui.quiz)};ui.back.onclick=()=>{if(index){index--;render()}};ui.restart.onclick=restart;ui.share.onclick=share})();
