(()=>{'use strict';
const MENUS=[{name:'제육볶음',emoji:'🥘'},{name:'돈까스',emoji:'🍛'},{name:'김치찌개',emoji:'🍲'},{name:'된장찌개',emoji:'🫕'},{name:'비빔밥',emoji:'🥗'},{name:'냉면',emoji:'🍜'},{name:'칼국수',emoji:'🍜'},{name:'쌀국수',emoji:'🍜'},{name:'짜장면',emoji:'🍝'},{name:'짬뽕',emoji:'🥣'},{name:'초밥',emoji:'🍣'},{name:'햄버거',emoji:'🍔'},{name:'피자',emoji:'🍕'},{name:'치킨',emoji:'🍗'},{name:'샌드위치',emoji:'🥪'},{name:'분식',emoji:'🍢'},{name:'부대찌개',emoji:'🍲'},{name:'순두부찌개',emoji:'🥘'},{name:'설렁탕',emoji:'🥣'},{name:'돼지국밥',emoji:'🍚'},{name:'닭갈비',emoji:'🍗'},{name:'보쌈',emoji:'🥩'},{name:'족발',emoji:'🍖'},{name:'삼겹살',emoji:'🥓'},{name:'떡볶이',emoji:'🌶️'},{name:'김밥',emoji:'🍙'},{name:'파스타',emoji:'🍝'},{name:'리조또',emoji:'🍚'},{name:'타코',emoji:'🌮'},{name:'샐러드',emoji:'🥗'},{name:'포케',emoji:'🍱'},{name:'도시락',emoji:'🍱'}];
const $=s=>document.querySelector(s),ui={battle:$('#battle'),result:$('#result'),round:$('#roundTitle'),current:$('#matchCurrent'),total:$('#matchTotal'),progress:$('#progressBar'),left:$('#leftChoice'),right:$('#rightChoice'),leftEmoji:$('#leftEmoji'),rightEmoji:$('#rightEmoji'),leftName:$('#leftName'),rightName:$('#rightName'),picked:$('#pickedList'),winnerEmoji:$('#winnerEmoji'),winnerName:$('#winnerName'),copyMessage:$('#copyMessage'),sound:$('#soundButton')};let round=[],winners=[],match=0,history=[],champion=null,locked=false,soundOn=true,audio;
function shuffle(items){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function roundName(n){return n===2?'결승':n+'강'}function pair(){return[round[match*2],round[match*2+1]]}
function render(){locked=false;ui.left.disabled=ui.right.disabled=false;ui.left.className='menu-card left';ui.right.className='menu-card right';const[a,b]=pair(),total=round.length/2;ui.round.textContent=roundName(round.length);ui.current.textContent=match+1;ui.total.textContent=total;ui.progress.style.width=((match+1)/total*100)+'%';ui.leftEmoji.textContent=a.emoji;ui.leftName.textContent=a.name;ui.rightEmoji.textContent=b.emoji;ui.rightName.textContent=b.name;ui.picked.replaceChildren(...history.slice(-7).map(m=>Object.assign(document.createElement('i'),{textContent:m.emoji+' '+m.name})))}
function choose(side){if(locked)return;locked=true;const choices=pair(),winner=choices[side],loser=choices[1-side];winners.push(winner);history.push(winner);ui.left.disabled=ui.right.disabled=true;(side?ui.right:ui.left).classList.add('winner');(side?ui.left:ui.right).classList.add('loser');play('pick');setTimeout(()=>{if(match+1<round.length/2){match++;render();return}if(winners.length===1){showResult(winner);return}round=[...winners];winners=[];match=0;render()},480)}
function showResult(winner){champion=winner;ui.battle.hidden=true;ui.result.hidden=false;ui.round.textContent='최종 선택';ui.current.textContent='✓';ui.total.textContent='완료';ui.progress.style.width='100%';ui.winnerEmoji.textContent=winner.emoji;ui.winnerName.textContent=winner.name;makeConfetti();play('win')}
function start(){round=shuffle(MENUS);winners=[];match=0;history=[];champion=null;ui.battle.hidden=false;ui.result.hidden=true;ui.copyMessage.textContent='';render();play('start')}
function makeConfetti(){const colors=['#7860d6','#ffd86c','#ff8f9f','#79d3b4'];$('#confetti').replaceChildren(...Array.from({length:28},(_,i)=>{const s=document.createElement('span');s.style.left=(Math.random()*100)+'%';s.style.background=colors[i%colors.length];s.style.animationDelay=(Math.random()*1.7)+'s';s.style.animationDuration=(1.7+Math.random())+'s';return s}))}
function play(type){if(!soundOn)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const notes=type==='win'?[523,659,784,1047]:type==='pick'?[440,660]:[392,523];notes.forEach((freq,i)=>{const at=audio.currentTime+i*.08,o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(.06,at+.015);g.gain.exponentialRampToValueAtTime(.0001,at+.13);o.connect(g).connect(audio.destination);o.start(at);o.stop(at+.15)})}catch{}}
async function copyResult(){if(!champion)return;const text='오늘 점심 월드컵 결과: '+champion.emoji+' '+champion.name+' 당첨!';try{await navigator.clipboard.writeText(text);ui.copyMessage.textContent='결과를 복사했어요!'}catch{ui.copyMessage.textContent=text}}
ui.left.addEventListener('click',()=>choose(0));ui.right.addEventListener('click',()=>choose(1));$('#restartButton').addEventListener('click',start);$('#shuffleButton').addEventListener('click',start);$('#copyButton').addEventListener('click',copyResult);ui.sound.addEventListener('click',()=>{soundOn=!soundOn;ui.sound.textContent=soundOn?'🔊':'🔇'});document.addEventListener('keydown',e=>{if(ui.result.hidden===false){if(e.key==='Enter')start();return}if(e.key==='1'||e.key==='ArrowLeft')choose(0);else if(e.key==='2'||e.key==='ArrowRight')choose(1)});start();
})();
