(() => {
  'use strict';
  const PUZZLES = [
    {id:1,title:'포근한 사무실',points:[[.64,.62,.07,.11,1],[.80,.17,.08,.13,1],[.14,.43,.10,.19,1],[.86,.65,.11,.23,1],[.26,.69,.08,.07,1]]},
    {id:2,title:'향긋한 카페',points:[[.50,.78,.10,.14,1],[.48,.30,.13,.08,1],[.22,.50,.07,.10,1],[.91,.57,.07,.11,1],[.84,.33,.14,.17,1]]},
    {id:3,title:'햇살 좋은 공원',points:[[.22,.38,.11,.13,1],[.55,.78,.38,.18,1],[.85,.75,.12,.18,1],[.90,.43,.08,.10,1],[.60,.39,.11,.11,1]]},
    {id:4,title:'따뜻한 주방',points:[[.16,.59,.09,.13,1],[.47,.48,.07,.15,1],[.64,.14,.09,.11,1],[.07,.29,.07,.21,1],[.76,.69,.08,.10,1]]},
    {id:5,title:'달콤한 베이커리',points:[[.56,.54,.07,.11,1],[.22,.38,.11,.17,1],[.52,.15,.15,.13,1],[.47,.90,.22,.06,1],[.19,.65,.06,.08,1]]}
  ];
  const params = new URLSearchParams(location.search);
  const ROUND_MS = location.hostname === '127.0.0.1' && params.has('fast') ? 1500 : 60000;
  const $ = selector => document.querySelector(selector);
  const ui = {
    gameCard:$('.game-card'),startScreen:$('#startScreen'),playScreen:$('#playScreen'),finishScreen:$('#finishScreen'),startButton:$('#startButton'),restartButton:$('#restartButton'),
    round:$('#roundNumber'),found:$('#foundNumber'),hearts:$('#hearts'),timer:$('#timer'),timeBar:$('#timeBar'),sceneNumber:$('#sceneNumber'),sceneTitle:$('#sceneTitle'),message:$('#message'),
    hintButton:$('#hintButton'),imageA:$('#imageA'),imageB:$('#imageB'),pictures:[...document.querySelectorAll('.picture')],finalTime:$('#finalTime'),finishIcon:$('#finishIcon'),
    finishEyebrow:$('#finishEyebrow'),finishTitle:$('#finishTitle'),finishText:$('#finishText')
  };
  let gamePuzzles=[],currentRound=0,found=new Set(),hearts=3,totalStartedAt=0,roundDeadline=0,timerId=null,busy=false,roundActive=false,hintUsed=false,audioContext;
  function shuffle(items){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}if(location.hostname==='127.0.0.1'&&params.has('scene')){const forced=Number(params.get('scene')),index=copy.findIndex(item=>item.id===forced);if(index>0)[copy[0],copy[index]]=[copy[index],copy[0]];}return copy;}
  const imagePath = (id,side) => `/images/spot-difference/puzzle-${String(id).padStart(2,'0')}-${side}.webp`;
  function formatElapsed(ms){const tenths=Math.floor(ms/100)%10,total=Math.floor(ms/1000),minutes=Math.floor(total/60),seconds=total%60;return `${String(minutes).padStart(2,'0')}:${String(seconds).padStart(2,'0')}.${tenths}`;}
  function updateHearts(){ui.hearts.textContent=Array.from({length:3},(_,i)=>i<hearts?'♥':'♡').join(' ');ui.hearts.setAttribute('aria-label',`남은 하트 ${hearts}개`);}
  function updateTimer(){if(!roundActive)return;const remaining=Math.max(0,roundDeadline-performance.now()),ratio=remaining/ROUND_MS,totalSeconds=Math.ceil(remaining/1000),minutes=Math.floor(totalSeconds/60),seconds=totalSeconds%60;ui.timer.textContent=`${String(minutes).padStart(2,'0')}:${String(seconds).padStart(2,'0')}`;ui.timeBar.style.width=`${ratio*100}%`;ui.timeBar.classList.toggle('warning',ratio<=.33&&ratio>.16);ui.timeBar.classList.toggle('danger',ratio<=.16);if(remaining<=0)handleTimeout();}
  async function preload(puzzles){await Promise.all(puzzles.flatMap(p=>['a','b'].map(side=>new Promise(resolve=>{const image=new Image();image.onload=image.onerror=resolve;image.src=imagePath(p.id,side);}))))}
  async function startGame(){if(busy)return;busy=true;ui.startButton.disabled=true;ui.startButton.textContent='그림 준비 중...';gamePuzzles=shuffle(PUZZLES).slice(0,3);await preload(gamePuzzles);currentRound=0;hearts=3;totalStartedAt=performance.now();updateHearts();clearInterval(timerId);timerId=setInterval(updateTimer,100);ui.startScreen.hidden=true;ui.finishScreen.hidden=true;ui.playScreen.hidden=false;await loadPuzzle();ui.startButton.disabled=false;ui.startButton.textContent='게임 시작';}
  async function loadPuzzle(){busy=true;roundActive=false;found=new Set();hintUsed=false;const puzzle=gamePuzzles[currentRound];ui.round.textContent=currentRound+1;ui.found.textContent='0';ui.sceneNumber.textContent=`SCENE ${String(puzzle.id).padStart(2,'0')}`;ui.sceneTitle.textContent=puzzle.title;ui.message.textContent='60초 안에 찾아보세요. 막히면 힌트를 사용하세요!';ui.hintButton.disabled=false;ui.hintButton.textContent='힌트 보기';ui.timeBar.className='';ui.timeBar.style.width='100%';ui.timer.textContent='01:00';ui.pictures.forEach(p=>{p.classList.remove('solved');p.querySelector('.markers').replaceChildren();p.disabled=true;});ui.imageA.src=imagePath(puzzle.id,'a');ui.imageB.src=imagePath(puzzle.id,'b');await Promise.all([ui.imageA.decode().catch(()=>{}),ui.imageB.decode().catch(()=>{})]);ui.pictures.forEach(p=>p.disabled=false);roundDeadline=performance.now()+ROUND_MS;roundActive=true;busy=false;}
  function addMarker(point,className='found-marker'){ui.pictures.forEach(p=>{const marker=document.createElement('i');marker.className=className;marker.style.left=`${point[0]*100}%`;marker.style.top=`${point[1]*100}%`;p.querySelector('.markers').append(marker);if(className==='hint-marker')setTimeout(()=>marker.remove(),2100);});}
  function showMiss(picture,x,y){const marker=document.createElement('i');marker.className='miss-marker';marker.style.left=`${x*100}%`;marker.style.top=`${y*100}%`;picture.querySelector('.markers').append(marker);setTimeout(()=>marker.remove(),450);}
  function playSound(correct){try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();const o=audioContext.createOscillator(),g=audioContext.createGain();o.type='sine';o.frequency.setValueAtTime(correct?620:180,audioContext.currentTime);if(correct)o.frequency.exponentialRampToValueAtTime(880,audioContext.currentTime+.09);g.gain.setValueAtTime(.0001,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.06,audioContext.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,audioContext.currentTime+.15);o.connect(g).connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+.16);}catch{}}
  function useHint(){if(busy||hintUsed)return;const remaining=gamePuzzles[currentRound].points.map((_,i)=>i).filter(i=>!found.has(i));if(!remaining.length)return;hintUsed=true;ui.hintButton.disabled=true;ui.hintButton.textContent='힌트 사용 완료';addMarker(gamePuzzles[currentRound].points[remaining[Math.floor(Math.random()*remaining.length)]],'hint-marker');ui.message.textContent='노란 원이 깜빡이는 곳을 자세히 살펴보세요!';}
  function handlePictureClick(event){if(busy||!roundActive)return;const picture=event.currentTarget,rect=picture.querySelector('img').getBoundingClientRect(),x=(event.clientX-rect.left)/rect.width,y=(event.clientY-rect.top)/rect.height;if(x<0||x>1||y<0||y>1)return;const puzzle=gamePuzzles[currentRound],match=puzzle.points.findIndex((point,i)=>{const radiusX=point[2]||.09,radiusY=point[3]||.09;if(found.has(i))return false;return point[4]?Math.abs(x-point[0])<=radiusX&&Math.abs(y-point[1])<=radiusY:Math.hypot((x-point[0])/radiusX,(y-point[1])/radiusY)<=1;});if(match<0){showMiss(picture,x,y);playSound(false);ui.message.textContent='조금만 더 살펴보세요. 막히면 힌트를 사용하세요!';return;}found.add(match);addMarker(puzzle.points[match]);playSound(true);ui.found.textContent=found.size;ui.message.textContent=found.size<5?`좋아요! 이제 ${5-found.size}개 남았어요.`:'이 장면의 차이를 모두 찾았어요!';if(found.size===5)completeRound();}
  function handleTimeout(){if(!roundActive)return;roundActive=false;hearts-=1;updateHearts();playSound(false);ui.gameCard.classList.remove('time-out');void ui.gameCard.offsetWidth;ui.gameCard.classList.add('time-out');if(hearts<=0){finishGame(false);return;}ui.message.textContent=`시간 초과! 하트가 1개 줄었어요. 힌트를 사용해보세요.`;roundDeadline=performance.now()+ROUND_MS;ui.timeBar.className='';ui.timeBar.style.width='100%';ui.timer.textContent='01:00';roundActive=true;}
  function completeRound(){busy=true;roundActive=false;ui.pictures.forEach(p=>{p.disabled=true;p.classList.add('solved');});if(currentRound<2){setTimeout(async()=>{currentRound+=1;await loadPuzzle();},900);return;}setTimeout(()=>finishGame(true),650);}
  function finishGame(success){roundActive=false;clearInterval(timerId);ui.playScreen.hidden=true;ui.finishScreen.hidden=false;ui.finalTime.textContent=formatElapsed(performance.now()-totalStartedAt);ui.finishIcon.textContent=success?'🏆':'💔';ui.finishEyebrow.textContent=success?'3문제 모두 완료!':'하트를 모두 사용했어요';ui.finishTitle.textContent=success?'전부 찾았어요':'아쉽지만 다시 도전!';ui.finishText.textContent=success?'총 걸린 시간':'이번 도전 시간';if(success)makeConfetti();else $('.confetti').replaceChildren();busy=false;}
  function makeConfetti(){const colors=['#8065d8','#ffd967','#ff7d9b','#79d3b4','#6fb7ed'];$('.confetti').replaceChildren(...Array.from({length:34},(_,i)=>{const p=document.createElement('span');p.style.left=`${Math.random()*100}%`;p.style.background=colors[i%colors.length];p.style.animationDelay=`${Math.random()*1.8}s`;p.style.animationDuration=`${1.8+Math.random()}s`;return p;}));}
  ui.startButton.addEventListener('click',startGame);ui.restartButton.addEventListener('click',startGame);ui.hintButton.addEventListener('click',useHint);ui.pictures.forEach(p=>p.addEventListener('click',handlePictureClick));
})();
