(()=>{'use strict';
const canvas=document.querySelector('#gameCanvas'),ctx=canvas.getContext('2d');
const $=s=>document.querySelector(s),els={score:$('#score'),height:$('#height'),combo:$('#combo'),lives:$('#lives'),overlay:$('#overlay'),title:$('#overlayTitle'),text:$('#overlayText'),message:$('#message'),next:$('#nextCup'),rank:$('#overlayRankingButton')};
const GAME={w:86,speed:175,accel:5},COLORS=['#ffad9f','#ffd96a','#8dddc3','#9fc7ff','#c6a9ef'];
const H=82,STEP=69,FLOOR=525;let phase='ready',score=0,height=0,combo=0,lives=3,perfects=0,tower=[],cup=null,nextColor=COLORS[0],dir=1,last=0,startAt=0,pausedFrom='',audioOn=true,audio,particles=[];
function randColor(){return COLORS[Math.floor(Math.random()*COLORS.length)]}
function baseCup(){return{x:150,y:FLOOR,w:120,color:'#d9d2e8'}}
function makeCup(){const color=nextColor;nextColor=randColor();els.next.style.background=nextColor;return{x:(canvas.width-GAME.w)/2,y:58,w:GAME.w,color,v:GAME.speed+GAME.accel*height}}
function reset(){score=height=combo=perfects=0;lives=3;tower=[baseCup()];cup=makeCup();phase='ready';startAt=0;particles=[];update();draw()}
function start(){reset();phase='moving';startAt=Date.now();hideOverlay();playSound('start');window.dispatchEvent(new CustomEvent('cupstack-game-start'))}
function hideOverlay(){els.overlay.classList.add('hidden')}function showOverlay(title,text,button='다시 도전'){els.title.textContent=title;els.text.textContent=text;$('#startButton').textContent=button;els.rank.hidden=true;els.overlay.classList.remove('hidden')}
function drop(){if(phase==='ready'||phase==='gameover'){start();return}if(phase!=='moving')return;phase='falling';playSound('drop')}
function land(){const top=tower[tower.length-1],left=Math.max(cup.x,top.x),right=Math.min(cup.x+cup.w,top.x+top.w),overlap=Math.max(0,right-left),min=cup.w*.22;if(overlap<min){miss();return}const diff=Math.abs((cup.x+cup.w/2)-(top.x+top.w/2)),perfect=diff<=7;if(perfect){cup.x=top.x+(top.w-cup.w)/2;combo++;perfects++;score+=120+combo*18;flash('PERFECT! +'+(120+combo*18));burst(cup.x+cup.w/2,cup.y,'#ffd96a');playSound('perfect')}else{combo=0;score+=Math.round(35+85*(overlap/cup.w));flash(overlap/cup.w>.65?'좋아요!':'아슬아슬!');playSound('land')}tower.push({...cup,y:top.y-STEP});height++;if(tower[tower.length-1].y<175)tower.forEach(c=>c.y+=STEP);cup=makeCup();phase='moving';update()}
function miss(){lives--;combo=0;update();flash('앗, 놓쳤어요!');if(lives<=0){finish();return}playSound('miss');cup=makeCup();phase='moving'}
function finish(){phase='gameover';const elapsed=Math.max(1,Math.floor((Date.now()-startAt)/1000));playSound('gameover');showOverlay('업무보다 높이 쌓았어요!','최종 '+score.toLocaleString()+'점 · '+height+'컵');els.rank.hidden=score<=0;window.dispatchEvent(new CustomEvent('cupstack-game-over',{detail:{score,height,perfects,elapsed}}))}
function pause(){if(phase==='moving'||phase==='falling'){pausedFrom=phase;phase='paused';showOverlay('잠깐 쉬는 중','준비되면 계속 쌓아볼까요?','계속하기')}else if(phase==='paused'){phase=pausedFrom;hideOverlay();last=performance.now()}}
function update(){els.score.textContent=score.toLocaleString();els.height.textContent=height;els.combo.textContent=combo;els.lives.textContent='♥'.repeat(lives)+'♡'.repeat(3-lives)}
function flash(t){els.message.textContent=t;els.message.classList.remove('show');void els.message.offsetWidth;els.message.classList.add('show')}
function burst(x,y,color){for(let i=0;i<18;i++)particles.push({x,y,vx:(Math.random()-.5)*180,vy:-60-Math.random()*100,life:1,color})}
function cupPath(c){const inset=Math.max(14,c.w*.15);ctx.beginPath();ctx.moveTo(c.x+4,c.y+7);ctx.lineTo(c.x+c.w-4,c.y+7);ctx.lineTo(c.x+c.w-inset,c.y+H-7);ctx.quadraticCurveTo(c.x+c.w-inset-2,c.y+H,c.x+c.w-inset-12,c.y+H);ctx.lineTo(c.x+inset+12,c.y+H);ctx.quadraticCurveTo(c.x+inset+2,c.y+H,c.x+inset,c.y+H-7);ctx.closePath()}
function drawCup(c){ctx.save();ctx.shadowColor='#53466b35';ctx.shadowBlur=8;ctx.shadowOffsetY=4;cupPath(c);ctx.fillStyle=c.color;ctx.fill();ctx.shadowColor='transparent';ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.stroke();ctx.beginPath();ctx.ellipse(c.x+c.w/2,c.y+7,c.w/2-3,7,0,0,Math.PI*2);ctx.fillStyle='#fff8';ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.stroke();ctx.beginPath();ctx.moveTo(c.x+18,c.y+18);ctx.lineTo(c.x+23,c.y+H-12);ctx.strokeStyle='#ffffff70';ctx.lineWidth=5;ctx.lineCap='round';ctx.stroke();ctx.restore()}
function draw(){const g=ctx.createLinearGradient(0,0,0,canvas.height);g.addColorStop(0,'#f2ecff');g.addColorStop(1,'#fff8e9');ctx.fillStyle=g;ctx.fillRect(0,0,420,620);ctx.fillStyle='#dcd4ed';ctx.fillRect(22,32,376,12);ctx.fillRect(22,515,376,8);ctx.fillStyle='#ffffff88';ctx.fillRect(36,54,348,95);ctx.fillStyle='#8b7ba6';ctx.font='800 15px system-ui';ctx.textAlign='center';ctx.fillText('SURVIVAL OFFICE PANTRY',210,94);tower.forEach(drawCup);if(cup)drawCup(cup);particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,4,0,Math.PI*2);ctx.fill()});ctx.globalAlpha=1}
function tick(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;if(phase==='moving'){cup.x+=cup.v*dir*dt;if(cup.x<=10){cup.x=10;dir=1}else if(cup.x+cup.w>=410){cup.x=410-cup.w;dir=-1}}else if(phase==='falling'){cup.y+=620*dt;const target=tower[tower.length-1].y-STEP;if(cup.y>=target){cup.y=target;land()}}particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=260*dt;p.life-=dt*1.7});particles=particles.filter(p=>p.life>0);draw();requestAnimationFrame(tick)}
function playSound(type){if(!audioOn)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const sounds={start:[[440,.00,.07],[660,.07,.10]],drop:[[310,.00,.04]],land:[[460,.00,.06],[610,.04,.08]],perfect:[[659,.00,.09],[784,.07,.10],[1047,.14,.16]],miss:[[240,.00,.10],[170,.09,.16]],gameover:[[330,.00,.13],[247,.12,.14],[165,.25,.22]]};(sounds[type]||sounds.land).forEach(([freq,delay,dur])=>{const when=audio.currentTime+delay,o=audio.createOscillator(),g=audio.createGain();o.type=type==='miss'||type==='gameover'?'triangle':'sine';o.frequency.setValueAtTime(freq,when);g.gain.setValueAtTime(.0001,when);g.gain.exponentialRampToValueAtTime(.075,when+.012);g.gain.exponentialRampToValueAtTime(.0001,when+dur);o.connect(g).connect(audio.destination);o.start(when);o.stop(when+dur+.02)})}catch{}}
canvas.addEventListener('pointerdown',drop);$('#dropButton').addEventListener('click',drop);$('#startButton').addEventListener('click',()=>phase==='paused'?pause():start());$('#pauseButton').addEventListener('click',pause);$('#newButton').addEventListener('click',()=>{reset();showOverlay('새 컵 탑 준비 완료!','화면이나 DROP 버튼을 눌러 시작하세요.','게임 시작')});$('#soundButton').addEventListener('click',e=>{audioOn=!audioOn;e.currentTarget.textContent=audioOn?'🔊':'🔇'});document.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();drop()}else if(e.key.toLowerCase()==='p'||e.key==='Escape')pause()});reset();requestAnimationFrame(tick);
})();
